name: Publish Package

on:
  push:
    tags:
      - "v*.*.*"   # Only run on version tags like v0.1.0

jobs:
  build:
    runs-on: ubuntu-latest
    environment: CARDUI_env

    env:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install build pytest twine

      - name: Check secrets exist
          run: |
          if [ -z "$OPENAI_API_KEY" ]; then echo "Missing OPENAI_API_KEY"; exit 1; fi
          echo "Secrets found (values masked)."

      - name: Set PYTHONPATH 
        run: echo "PYTHONPATH=src" >> $GITHUB_ENV
          
      - name: Run tests
        run: pytest

      - name: Build package
        run: |
          python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload --repository-url https://test.pypi.org/legacy/ dist/*
